### ISSUE TITLE
Not clear what is it in the other side

### ISSUE THREAD

**Issue by darvidor** [skiwithpete/relaypi#1]
Nice video about those scripts. This part is clear. I guess your relay also have "protection" (optoisolator). Anyway, what is not clear in the video is what I can connect in the other side. I mean, if I have a device which works with 12V how I need to connect it to the relaY? Any VCC source with 12V?

thank you and sorry for those questions. I need to update my electronics knowldge.

**Comment by skiwithpete** [comment]
You should get the relay working before you worry about wiring it.  Also, I
hesitate to share how the otherside works as it may differ by relay.
However, I did show it in this video:
https://www.youtube.com/watch?v=3u45htuQeag
